apiVersion: apps/v1
kind: Deployment
metadata:
  name: monu
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: example-container
          image: monutiwaricode/nginx-ubuntu
          ports:
            - containerPort: 8082